services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cse400
      POSTGRES_PASSWORD: cse400
      POSTGRES_DB: cse400
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  preprocess:
    build: ./services/preprocess_service
    environment:
      API_KEY: ${API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALG: ${JWT_ALG}
      JWT_ISSUER: ${JWT_ISSUER}
      RETURN_OCR_TEXT: ${RETURN_OCR_TEXT}
      SPACY_MODEL: en_core_web_sm
    ports:
      - "8001:8001"

  patient-store:
    build: ./services/patient_store_service
    environment:
      API_KEY: ${API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALG: ${JWT_ALG}
      JWT_ISSUER: ${JWT_ISSUER}
      DATABASE_URL: ${DATABASE_URL}
      STORAGE_DIR: ${STORAGE_DIR}
      FILE_ENCRYPTION_KEY: ${FILE_ENCRYPTION_KEY}
    depends_on:
      - db
    ports:
      - "8002:8002"
    volumes:
      - patient_docs:${STORAGE_DIR}

  inference:
    build: ./services/inference_service
    environment:
      API_KEY: ${API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALG: ${JWT_ALG}
      JWT_ISSUER: ${JWT_ISSUER}
      PATIENT_STORE_URL: ${PATIENT_STORE_URL}
      MODEL_BUNDLE_DIR: ${MODEL_BUNDLE_DIR}
    depends_on:
      - patient-store
    ports:
      - "8003:8003"
    volumes:
      - ./model_bundle:${MODEL_BUNDLE_DIR}:ro

  auth:
    build: ./services/auth_service
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALG: ${JWT_ALG}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXP_SECONDS: ${JWT_EXP_SECONDS}
      USERS_FILE: ${USERS_FILE}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8004:8004"
    volumes:
      - auth_data:/data

  web-portal:
    build: ./services/web_portal
    environment:
      AUTH_URL: ${AUTH_URL}
      PREPROCESS_URL: ${PREPROCESS_URL}
      PATIENT_STORE_URL: ${PATIENT_STORE_URL}
      INFERENCE_URL: ${INFERENCE_URL}
      COOKIE_SECURE: "false"
    depends_on:
      - auth
      - preprocess
      - patient-store
      - inference
    ports:
      - "8000:8000"

volumes:
  db_data:
  patient_docs:
  auth_data:
